# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:28
from __future__ import unicode_literals

import Task.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Translator', '__first__'),
        ('News', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_translator', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('upload', models.FileField(default=Task.models.path, upload_to=b'article/%Y/%m/%d/', validators=[Task.models.validate_file_extension, Task.models.validate_file_size])),
                ('expiration_date', models.DateTimeField()),
                ('news_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='News.News')),
                ('translator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Translator.Translator')),
            ],
        ),
    ]
