# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:51
from __future__ import unicode_literals

import Task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='upload',
            field=models.FileField(default=Task.models.path, upload_to=b'article/%Y/%m/%d/', validators=[Task.models.validate_file_extension, Task.models.validate_file_size]),
        ),
    ]
