# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Translator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='family_name',
            new_name='family',
        ),
    ]
